In [2]:
from datetime import datetime

import backtrader as bt  # 升级到最新版
import matplotlib.pyplot as plt  # 由于 Backtrader 的问题，此处要求 pip install matplotlib==3.2.2
import akshare as ak  # 升级到最新版
import pandas as pd

plt.rcParams["font.sans-serif"] = ["SimHei"]
plt.rcParams["axes.unicode_minus"] = False

# 上海证券交易所-股票数据总貌

目标地址: http://www.sse.com.cn/market/stockdata/statistic/

In [ ]:
stock_sse_summary_df = ak.stock_sse_summary()
stock_sse_summary_df

# 深圳证券交易所-市场总貌-证券类别统计

目标地址: http://www.szse.cn/market/overview/index.html

In [ ]:
stock_szse_summary_df = ak.stock_szse_summary(date="20250228")
stock_szse_summary_df

# 深圳证券交易所-市场总貌-地区交易排序

目标地址: http://www.szse.cn/market/overview/index.html

In [ ]:
stock_szse_area_summary_df = ak.stock_szse_area_summary(date="202501")
stock_szse_area_summary_df

#  深圳证券交易所-统计资料-股票行业成交数据

目标地址: http://docs.static.szse.cn/www/market/periodical/month/W020220511355248518608.html

In [ ]:
stock_szse_sector_summary_df = ak.stock_szse_sector_summary(symbol="当年", date="202501")
stock_szse_sector_summary_df

# 上海证券交易所-数据-股票数据-成交概况-股票成交概况-每日股票情况

目标地址: http://www.sse.com.cn/market/stockdata/overview/day/

In [ ]:
stock_sse_deal_daily_df = ak.stock_sse_deal_daily(date="20250227")
stock_sse_deal_daily_df

 # 东方财富-个股-股票信息

目标地址: http://quote.eastmoney.com/concept/sh603777.html?from=classic

In [ ]:
stock_individual_info_em_df = ak.stock_individual_info_em(symbol='000002')
stock_individual_info_em_df

# 东方财富-行情报价

目标地址: https://quote.eastmoney.com/sz000001.html

In [ ]:
stock_bid_ask_em_df = ak.stock_bid_ask_em(symbol="000001")
stock_bid_ask_em_df

# 东方财富网-沪深京 A 股-实时行情数据

目标地址: https://quote.eastmoney.com/center/gridlist.html#hs_a_board

In [ ]:
stock_zh_a_spot_em_df = ak.stock_zh_a_spot_em()
stock_zh_a_spot_em_df

In [ ]:
stock_zh_a_spot_em_df.columns

In [ ]:
stock_zh_a_spot_em_df.index

# 东方财富网-沪 A 股-实时行情数据

目标地址: http://quote.eastmoney.com/center/gridlist.html#sh_a_board

In [25]:
stock_sh_a_spot_em_df = ak.stock_sh_a_spot_em()
stock_sh_a_spot_em_df

,序号,代码,名称,最新价,涨跌幅,涨跌额,成交量,成交额,振幅,最高,...,量比,换手率,市盈率-动态,市净率,总市值,流通市值,涨速,5分钟涨跌,60日涨跌幅,年初至今涨跌幅
0,1,688598,金博股份,29.20,10.73,2.83,393888.0,1.207652e+09,10.01,31.64,...,3.02,19.29,-7.68,1.14,5.961411e+09,5.961411e+09,-0.17,-0.14,8.75,38.65
1,2,600665,天地源,3.26,10.14,0.30,931750.0,2.980960e+08,7.43,3.26,...,6.86,10.78,21.05,0.70,2.817039e+09,2.817039e+09,0.00,0.00,0.00,4.15
2,3,600734,实达集团,4.80,10.09,0.44,2449878.0,1.166380e+09,6.65,4.80,...,1.77,11.30,214.57,24.38,1.045585e+10,1.040845e+10,0.00,0.00,20.60,32.96
3,4,600693,东百集团,6.78,10.06,0.62,1659214.0,1.062581e+09,10.88,6.78,...,2.39,19.09,51.76,1.67,5.897558e+09,5.891500e+09,0.00,0.00,72.08,-3.14
4,5,601789,宁波建工,6.13,10.05,0.56,1516248.0,8.986309e+08,10.41,6.13,...,0.83,13.95,22.76,1.52,6.662075e+09,6.662075e+09,0.00,0.00,34.73,38.06
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2397,2398,688691,灿芯股份,86.15,-14.70,-14.85,60029.0,5.387302e+08,12.66,98.00,...,1.05,23.54,169.39,7.57,1.033800e+10,2.196825e+09,0.06,0.16,12.47,11.88
2398,2399,688655,迅捷兴,13.49,-14.89,-2.36,164747.0,2.269922e+08,16.40,15.81,...,1.39,12.35,-950.32,2.64,1.799431e+09,1.799431e+09,0.52,0.90,19.27,25.14
2399,2400,688165,埃夫特-U,32.95,-15.47,-6.03,488139.0,1.682211e+09,12.75,37.85,...,0.90,9.36,-118.02,10.46,1.719265e+10,1.719265e+10,-0.09,-0.96,102.40,24.81
2400,2401,688629,华丰科技,61.28,-15.89,-11.58,357215.0,2.345099e+09,14.14,71.00,...,1.09,20.03,-1527.37,19.35,2.824964e+10,1.092779e+10,-0.07,0.13,80.87,82.98
2401,2402,688327,云从科技-UW,20.04,-15.94,-3.80,2117237.0,4.509424e+09,13.80,23.12,...,1.15,28.15,-32.61,17.67,2.078025e+10,1.507026e+10,-0.10,-1.04,59.05,65.62

#  东方财富网-深 A 股-实时行情数据

目标地址: http://quote.eastmoney.com/center/gridlist.html#sz_a_board

In [ ]:
stock_sz_a_spot_em_df = ak.stock_sz_a_spot_em()
stock_sz_a_spot_em_df

#  东方财富网-京 A 股-实时行情数据

目标地址: http://quote.eastmoney.com/center/gridlist.html#bj_a_board

In [ ]:
stock_bj_a_spot_em_df = ak.stock_bj_a_spot_em()
stock_bj_a_spot_em_df

# 东方财富网-新股-实时行情数据

目标地址: http://quote.eastmoney.com/center/gridlist.html#newshares

In [ ]:
stock_new_a_spot_em_df = ak.stock_new_a_spot_em()
stock_new_a_spot_em_df

# 东方财富网-创业板-实时行情

目标地址: https://quote.eastmoney.com/center/gridlist.html#gem_board

In [ ]:
stock_cy_a_spot_em_df = ak.stock_cy_a_spot_em()
stock_cy_a_spot_em_df

#  东方财富网-科创板-实时行情

目标地址: http://quote.eastmoney.com/center/gridlist.html#kcb_board

In [ ]:
stock_kc_a_spot_em_df = ak.stock_kc_a_spot_em()
stock_kc_a_spot_em_df

# 新浪财经-沪深京 A 股数据, 重复运行本函数会被新浪暂时封 IP, 建议增加时间间隔

目标地址: https://vip.stock.finance.sina.com.cn/mkt/#hs_a

In [ ]:
stock_zh_a_spot_df = ak.stock_zh_a_spot()
stock_zh_a_spot_df

# 雪球-行情中心-个股

目标地址: https://xueqiu.com/S/SH513520

In [6]:
stock_individual_spot_xq_df = ak.stock_individual_spot_xq(symbol="SH600000")
stock_individual_spot_xq_df.dtypes

KeyError: 'data'

#  东方财富-沪深京 A 股日频率数据; 历史数据按日频率更新, 当日收盘价请在收盘后获取

目标地址: https://quote.eastmoney.com/concept/sh603777.html?from=classic(示例)

In [3]:
# 数据示例-历史行情数据-不复权
stock_zh_a_hist_df = ak.stock_zh_a_hist(symbol="000001", period="daily", start_date="20170301", end_date='20240528', adjust="")
stock_zh_a_hist_df

,日期,股票代码,开盘,收盘,最高,最低,成交量,成交额,振幅,涨跌幅,涨跌额,换手率
0,2017-03-01,000001,9.49,9.49,9.55,9.47,346994,3.301580e+08,0.84,0.11,0.01,0.21
1,2017-03-02,000001,9.51,9.43,9.54,9.42,403629,3.823959e+08,1.26,-0.63,-0.06,0.24
2,2017-03-03,000001,9.41,9.40,9.43,9.36,342655,3.219525e+08,0.74,-0.32,-0.03,0.20
3,2017-03-06,000001,9.40,9.45,9.46,9.39,404511,3.812123e+08,0.74,0.53,0.05,0.24
4,2017-03-07,000001,9.44,9.45,9.46,9.40,294673,2.777474e+08,0.63,0.00,0.00,0.17
...,...,...,...,...,...,...,...,...,...,...,...,...
1755,2024-05-22,000001,11.56,11.56,11.74,11.46,2115531,2.458449e+09,2.42,0.09,0.01,1.09
1756,2024-05-23,000001,11.53,11.40,11.59,11.37,1841623,2.110799e+09,1.90,-1.38,-0.16,0.95
1757,2024-05-24,000001,11.37,11.31,11.49,11.30,1398276,1.593330e+09,1.67,-0.79,-0.09,0.72
1758,2024-05-27,000001,11.31,11.51,11.53,11.31,1454361,1.663272e+09,1.95,1.77,0.20,0.75
1759,2024-05-28,000001,11.50,11.40,11.58,11.36,1204323,1.377107e+09,1.91,-0.96,-0.11,0.62

In [4]:
# 接口示例-历史行情数据-前复权
stock_zh_a_hist_df = ak.stock_zh_a_hist(symbol="000001", period="daily", start_date="20170301", end_date='20240528', adjust="qfq")
stock_zh_a_hist_df

,日期,股票代码,开盘,收盘,最高,最低,成交量,成交额,振幅,涨跌幅,涨跌额,换手率
0,2017-03-01,000001,7.18,7.18,7.24,7.16,346994,3.301580e+08,1.12,0.14,0.01,0.21
1,2017-03-02,000001,7.20,7.12,7.23,7.11,403629,3.823959e+08,1.67,-0.84,-0.06,0.24
2,2017-03-03,000001,7.10,7.09,7.12,7.05,342655,3.219525e+08,0.98,-0.42,-0.03,0.20
3,2017-03-06,000001,7.09,7.14,7.15,7.08,404511,3.812123e+08,0.99,0.71,0.05,0.24
4,2017-03-07,000001,7.13,7.14,7.15,7.09,294673,2.777474e+08,0.84,0.00,0.00,0.17
...,...,...,...,...,...,...,...,...,...,...,...,...
1755,2024-05-22,000001,10.60,10.60,10.78,10.50,2115531,2.458449e+09,2.64,0.09,0.01,1.09
1756,2024-05-23,000001,10.57,10.44,10.63,10.41,1841623,2.110799e+09,2.08,-1.51,-0.16,0.95
1757,2024-05-24,000001,10.41,10.35,10.53,10.34,1398276,1.593330e+09,1.82,-0.86,-0.09,0.72
1758,2024-05-27,000001,10.35,10.55,10.57,10.35,1454361,1.663272e+09,2.13,1.93,0.20,0.75
1759,2024-05-28,000001,10.54,10.44,10.62,10.40,1204323,1.377107e+09,2.09,-1.04,-0.11,0.62

In [5]:
# 接口示例-历史行情数据-后复权
stock_zh_a_hist_df = ak.stock_zh_a_hist(symbol="000001", period="daily", start_date="20170301", end_date='20240528', adjust="hfq")
stock_zh_a_hist_df

,日期,股票代码,开盘,收盘,最高,最低,成交量,成交额,振幅,涨跌幅,涨跌额,换手率
0,2017-03-01,000001,1575.20,1575.20,1584.95,1571.95,346994,3.301580e+08,0.83,0.10,1.63,0.21
1,2017-03-02,000001,1578.45,1565.45,1583.32,1563.82,403629,3.823959e+08,1.24,-0.62,-9.75,0.24
2,2017-03-03,000001,1562.20,1560.57,1565.45,1554.07,342655,3.219525e+08,0.73,-0.31,-4.88,0.20
3,2017-03-06,000001,1560.57,1568.70,1570.32,1558.95,404511,3.812123e+08,0.73,0.52,8.13,0.24
4,2017-03-07,000001,1567.07,1568.70,1570.32,1560.57,294673,2.777474e+08,0.62,0.00,0.00,0.17
...,...,...,...,...,...,...,...,...,...,...,...,...
1755,2024-05-22,000001,2131.04,2131.04,2160.30,2114.79,2115531,2.458449e+09,2.14,0.08,1.62,1.09
1756,2024-05-23,000001,2126.17,2105.04,2135.92,2100.16,1841623,2.110799e+09,1.68,-1.22,-26.00,0.95
1757,2024-05-24,000001,2100.16,2090.41,2119.67,2088.79,1398276,1.593330e+09,1.47,-0.69,-14.63,0.72
1758,2024-05-27,000001,2090.41,2122.92,2126.17,2090.41,1454361,1.663272e+09,1.71,1.56,32.51,0.75
1759,2024-05-28,000001,2121.29,2105.04,2134.29,2098.54,1204323,1.377107e+09,1.68,-0.84,-17.88,0.62

# 新浪财经-沪深京 A 股的数据, 历史数据按日频率更新

目标地址: https://finance.sina.com.cn/realstock/company/sh600006/nc.shtml(示例)

P.S. 建议切换为 stock_zh_a_hist 接口使用(该接口数据质量高, 访问无限制)

注意其中的 **sh689009** 为 CDR, 请 通过 **ak.stock_zh_a_cdr_daily** 接口获取

In [9]:
# 数据示例-历史行情数据(前复权)
stock_zh_a_daily_qfq_df = ak.stock_zh_a_daily(symbol="sz000001", start_date="19910403", end_date="20231027", adjust="qfq")
stock_zh_a_daily_qfq_df

,date,open,high,low,close,volume,amount,outstanding_share,turnover
0,1991-04-03,0.35,0.35,0.35,0.35,100.0,5.000000e+03,3.710000e+07,0.000003
1,1991-04-04,0.35,0.35,0.35,0.35,300.0,1.500000e+04,3.710000e+07,0.000008
2,1991-04-05,0.35,0.35,0.35,0.35,200.0,1.000000e+04,3.710000e+07,0.000005
3,1991-04-08,0.35,0.35,0.35,0.35,200.0,1.000000e+04,3.710000e+07,0.000005
4,1991-04-09,0.34,0.34,0.34,0.34,400.0,1.900000e+04,3.710000e+07,0.000011
...,...,...,...,...,...,...,...,...,...
7730,2023-10-23,9.68,9.69,9.53,9.59,53040448.0,5.570322e+08,1.940555e+10,0.002733
7731,2023-10-24,9.63,9.70,9.54,9.64,76065269.0,8.015284e+08,1.940555e+10,0.003920
7732,2023-10-25,9.60,9.63,9.47,9.48,141144968.0,1.470972e+09,1.940555e+10,0.007273
7733,2023-10-26,9.42,9.52,9.41,9.51,59999147.0,6.219153e+08,1.940555e+10,0.003092
7734,2023-10-27,9.48,9.58,9.44,9.55,91977136.0,9.575875e+08,1.940555e+10,0.004740

In [10]:
# 接口示例-前复权因子

qfq_factor_df = ak.stock_zh_a_daily(symbol="sz000002", adjust="qfq-factor")
qfq_factor_df

         date            qfq_factor
0  2023-08-25    1.0000000000000000
1  2022-08-25    1.0517754291451000
2  2021-08-25    1.1168798473057000
3  2020-08-14    1.1810093745970000
4  2019-08-15    1.2245366427798000
5  2018-08-23    1.2735981991808000
6  2017-08-29    1.3233913520593000
7  2016-07-29    1.3684162947004000
8  2015-07-21    1.4256988372693000
9  2014-05-08    1.4737021651235000
10 2013-05-16    1.5546965200431000
11 2012-07-05    1.5798398599899000
12 2011-05-27    1.6027105929296000
13 2010-05-18    1.6232581646338000
14 2009-06-08    1.6398462042724000
15 2008-06-16    1.6475522484654000
16 2007-05-16    2.6521572780175000
17 2006-07-21    4.0043855834397000
18 2005-06-29    4.1056769557021000
19 2004-05-26    6.3462750504298000
20 2003-05-23    9.5848830885446000
21 2002-07-17   19.4514673699928000
22 2001-08-21   19.7687833140383020
23 2000-08-17   20.0160648287379000
24 2000-01-10   20.2241320306998030
25 1999-08-06   21.7007260053956000
26 1998-07-10   24.0549868667835000
27 1997-07-14   26.7769985385511000
28 1997-06-27   31.2296603923877000
29 1996-08-06   36.0689784010141000
30 1995-07-04   40.3371408451341000
31 1994-06-21   47.9136235499274000
32 1993-04-05   65.9178076663026900
33 1992-03-30   99.0712868582592000
34 1991-06-10  118.8855442299110900
35 1991-01-29  169.1453113717332000
36 1900-01-01  169.1453113717332000

#  腾讯证券-日频-股票历史数据; 历史数据按日频率更新, 当日收盘价请在收盘后获取

目标地址: https://gu.qq.com/sh000919/zs

限量: 单次返回指定沪深京 A 股上市公司、指定周期和指定日期间的历史行情日频率数据

In [12]:
# 数据示例-不复权

stock_zh_a_hist_tx_df = ak.stock_zh_a_hist_tx(symbol="sz000001", start_date="20200101", end_date="20231027", adjust="")
stock_zh_a_hist_tx_df

ImportError: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html

In [13]:
# 接口示例-前复权

stock_zh_a_hist_tx_df = ak.stock_zh_a_hist_tx(symbol="sz000001", start_date="20200101", end_date="20231027", adjust="qfq")
print(stock_zh_a_hist_tx_df)

ImportError: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html

#  新浪财经-沪深京 A 股股票或者指数的分时数据，目前可以获取 1, 5, 15, 30, 60 分钟的数据频率, 可以指定是否复权

 新浪财经-沪深京 A 股股票或者指数的分时数据，目前可以获取 1, 5, 15, 30, 60 分钟的数据频率, 可以指定是否复权

 限量: 单次返回指定股票或指数的指定频率的最近交易日的历史分时行情数据; 注意调用频率

In [15]:
stock_zh_a_minute_df = ak.stock_zh_a_minute(symbol='sh600751', period='1', adjust="qfq")
stock_zh_a_minute_df

                      day  open  high   low  close  volume
0     2025-02-18 13:53:00  2.52  2.53  2.52   2.52    1300
1     2025-02-18 13:54:00  2.53  2.53  2.52   2.52   30700
2     2025-02-18 13:55:00  2.52  2.52  2.52   2.52     800
3     2025-02-18 13:56:00  2.52  2.52  2.52   2.52   28900
4     2025-02-18 13:57:00  2.52  2.53  2.52   2.53   21900
...                   ...   ...   ...   ...    ...     ...
1965  2025-02-28 14:54:00  2.45  2.45  2.44   2.45  379600
1966  2025-02-28 14:55:00  2.45  2.45  2.44   2.45  400600
1967  2025-02-28 14:56:00  2.45  2.46  2.44   2.45  349235
1968  2025-02-28 14:57:00  2.45  2.46  2.45   2.46  210000
1969  2025-02-28 15:00:00  2.45  2.45  2.45   2.45  292100

[1970 rows x 6 columns]

#  东方财富网-行情首页-沪深京 A 股-每日分时行情; 该接口只能获取近期的分时数据，注意时间周期的设置

目标地址: https://quote.eastmoney.com/concept/sh603777.html

限量: 单次返回指定股票、频率、复权调整和时间区间的分时数据, 其中 1 分钟数据只返回近 5 个交易日数据且不复权
输入参数

| 名称         | 类型  | 描述                                                                                                  |
|------------|-----|-----------------------------------------------------------------------------------------------------|
| symbol     | str | symbol='000300'; 股票代码                                                                               |
| start_date | str | start_date="1979-09-01 09:32:00"; 日期时间; 默认返回所有数据                                                    |
| end_date   | str | end_date="2222-01-01 09:32:00"; 日期时间; 默认返回所有数据                                                      |
| period     | str | period='5'; choice of {'1', '5', '15', '30', '60'}; 其中 1 分钟数据返回近 5 个交易日数据且不复权                       |
| adjust     | str | adjust=''; choice of {'', 'qfq', 'hfq'}; '': 不复权, 'qfq': 前复权, 'hfq': 后复权, 其中 1 分钟数据返回近 5 个交易日数据且不复权 |

输出参数-1分钟数据

| 名称  | 类型      | 描述      |
|-----|---------|---------|
| 时间  | object  | -       |
| 开盘  | float64 | -       |
| 收盘  | float64 | -       |
| 最高  | float64 | -       |
| 最低  | float64 | -       |
| 成交量 | float64 | 注意单位: 手 |
| 成交额 | float64 | -       |
| 均价  | float64 | -       |

In [21]:
# 注意：该接口返回的数据只有最近一个交易日的有开盘价，其他日期开盘价为 0
# stock_zh_a_hist_min_em_df = ak.stock_zh_a_hist_min_em(symbol="000001", start_date="2025-02-27 09:30:00", end_date="2025-02-27 15:00:00", period="1", adjust="")
stock_zh_a_hist_min_em_df = ak.stock_zh_a_hist_min_em(symbol="000001", period="1", adjust="")
stock_zh_a_hist_min_em_df

,时间,开盘,收盘,最高,最低,成交量,成交额,均价
0,2025-02-24 09:30:00,0.00,11.63,11.63,11.63,7982,9283066.0,11.630
1,2025-02-24 09:31:00,0.00,11.60,11.62,11.59,22516,26145707.0,11.617
2,2025-02-24 09:32:00,0.00,11.58,11.60,11.56,14717,17041264.0,11.605
3,2025-02-24 09:33:00,0.00,11.62,11.62,11.59,10433,12101111.0,11.604
4,2025-02-24 09:34:00,0.00,11.65,11.66,11.63,31025,36114797.0,11.617
...,...,...,...,...,...,...,...,...
1200,2025-02-28 14:56:00,11.50,11.51,11.53,11.50,13760,15841187.0,11.596
1201,2025-02-28 14:57:00,11.52,11.51,11.52,11.50,6895,7936036.0,11.595
1202,2025-02-28 14:58:00,11.51,11.51,11.51,11.51,42,48342.0,11.595
1203,2025-02-28 14:59:00,11.51,11.51,11.51,11.51,0,0.0,11.595
1204,2025-02-28 15:00:00,11.53,11.53,11.53,11.53,26623,30696318.0,11.594

# 东财财富-分时数据

目标地址: https://quote.eastmoney.com/f1.html?newcode=0.000001

单次返回指定股票最近一个交易日的分时数据, 包含盘前数据

输入参数

| 名称         | 类型  | 描述                                  |
|------------|-----|-------------------------------------|
| symbol     | str | symbol="000001"; 股票代码               |

输出参数

| 名称    | 类型      | 描述 |
|-------|---------|----|
| 时间    | object  | -  |
| 成交价   | float64 | -  |
| 手数    | int64   | -  |
| 买卖盘性质 | object  | -  |

In [24]:
stock_intraday_em_df = ak.stock_intraday_em(symbol="000001")
stock_intraday_em_df

            时间    成交价     手数 买卖盘性质
0     09:15:00  11.62     91   中性盘
1     09:15:09  11.62    680   中性盘
2     09:15:18  11.62    682   中性盘
3     09:15:36  11.62    685   中性盘
4     09:15:45  11.60    903   中性盘
...        ...    ...    ...   ...
4457  14:56:51  11.50    223    卖盘
4458  14:56:54  11.51    255    买盘
4459  14:56:57  11.51     10    买盘
4460  14:57:00  11.51     42    买盘
4461  15:00:00  11.53  26623    买盘

[4462 rows x 4 columns]